### PR TITLE
Suggest %APPDATA%\inkscape\extensions folder on Windows

### PR DESCRIPTION
**Pull request by jeremycook**
`%ProgramFiles%` will automatically resolve to the correct folder on Windows regardless of locale. For example, my program files folder is "C:\Program Files"

### CODE REVIEW

**Comment by Moini** [comment]
That's the wrong location, as far as I know, anyway.

Changes there will be lost when Inkscape is updated.

C:\Users\user name\AppData\Roaming\Inkscape should be used.

Is there a generic name for that folder, too?

**Comment by giacmir** [comment]
Hi @jeremycook,
thanks for your contribution.

I agree that "Programes" is not the correct phrasing for documentation, but since I'm not using windows from a while I can't say which is the correct way to specify "that" folder. Also the point from @Moini is valid. 

In general, where do you put inskcape extensions on windows? I can't find documentation on topic.

**Comment by Moini** [comment]
@giacmir The generic instructions for each OS are as follows:

- Open Inkscape
- Open the preferences at Edit > Preferences > System
- Open the folder listed at 'User extensions'
- Drop the .py and .inx file there

(Inkscape knows where it looks for extensions, so that's the universal way to know where to put them)

**Comment by Moini** [comment]
See also:  
https://inkscape.org/learn/faq/#how-install-new-extensions-palettes-document-templates-symbol-sets-icon-sets-etc  
https://inkscape.org/gallery/=extension/

**Comment by giacmir** [comment]
Ok, so I suggest to use these instructions instead of specifying each path for each OS.

**Comment by jeremycook** [comment]
Ah yes you are right @Moini that it extensions should be placed under the user's home directory. @giacmir I've committed another change that uses the current user's %APPDATA% folder instead of the machine-wide program files folder.

**Comment by giacmir** [comment]
Thank you @jeremycook

**Comment by Moini** [comment]
Thank you from me, too, @jeremycook!

**Pull request merged**
