### PR TITLE
Export to webp (if available in imagemagick) in addition to jpg

### PR DESCRIPTION
**Pull request by Moini**
Hi Giacomo,

I've finally been able to test if my webp export works when imagemagick actually supports it. Could you take a look, and merge if you think it makes sense? I know it doesn't exactly fit the extension name, but it would enrich the options users have.

### CODE REVIEW

**Comment by giacmir** [comment]
Hi @Moini, thanks for your request. 
I don't have any issue about including webp support, only I'd prefer to wait that imagemagick has webp support at least in ubuntu.

**Comment by Moini** [comment]
@giacmir: That makes sense. Not everyone wants to compile im themselves and put the packages on hold... But when they download, they might expect it to just work (on Windows, it probably does - well, at least we get security fixes, while they don't... ;-) ).

**Comment by dubis** [comment]
Hi Giacomo, 

great job but doesn't work any more with python 3.6 as 

pip3 install index
Collecting index
  Using cached index-0.2.tar.gz
Collecting PySide (from index)
  Using cached PySide-1.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-imaq9x1k/PySide/

I'm not very strong in python, I can not download PySide2 by the way after reading on the web

**Comment by giacmir** [comment]
Hi @dubis 

1. This is not the right place to put you request, please open a new issue instead of commenting on existing ones
2. I don't understand what are you doing and how is related to my inkscape extension. When you open your new issue please add more details on what is not working and why are you using pip for this

**Comment by dubis** [comment]
Sorry I'm newbie on github too 
You could erase all my comment I found an issue 
The root cause was inkscape did not find the index module that's it

**Comment by giacmir** [comment]
Hi @Moini,
this pull request has remained pending for too much time!

I'm a bit in doubt about it. My extension is about saving as Jpeg, and I fear that adding a second image output format can be a bit out of scope. I think that perhaps this feature should have an extension on its own.

**Comment by Moini** [comment]
It's fine - thanks for getting back to me! I see you're doing some spring cleaning ;-)

**Pull request closed without merging**
